### PR TITLE
fix #573

### LINKED ISSUE #573: Generated tests do not compile
**Describe the bug**
The generated test case class (`<crawl_dir>/src/test/java/generated/GeneratedTests.java`) does not compile:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project generated-test: Compilation failure: Compilation failure: 
[ERROR] .../crawl0/src/test/java/generated/GeneratedTests.java:[46,131] ')' expected
[ERROR] .../crawl0/src/test/java/generated/GeneratedTests.java:[46,146] not a statement
[ERROR] .../crawl0/src/test/java/generated/GeneratedTests.java:[46,150] ';' expected
```
Corresponding test code:
```
builder.setBrowserConfig(new BrowserConfiguration(BrowserType.CHROME_HEADLESS, 1, new BrowserOptions( pixelDensity: 1, USE_CDP : true)));
```

The POM velocity template probably needs to be updated (Java compiler version, crawljax dependency).

### PR DESCRIPTION
**Pull request by yrahulkr**

### CODE REVIEW

File: plugins/testcasegenerator-plugin/src/main/java/com/crawljax/plugins/testcasegenerator/JavaTestGenerator.java [hunk 1]
```diff
@@ -150,7 +160,8 @@ private Object getBrowserConfigString(BrowserConfiguration browserConfig) {
             builder.append(", ");
             builder.append(browserConfig.getNumberOfBrowsers());
             builder.append(", ");
-            builder.append("new " + browserConfig.getBrowserOptions().toString());
+            builder.append("new " + getBrowserOptionsString(browserConfig.getBrowserOptions()));
+            //            builder.append("new " + browserConfig.getBrowserOptions().toString());
```
Comment (amesbah) [inline plugins/testcasegenerator-plugin/src/main/java/com/crawljax/plugins/testcasegenerator/JavaTestGenerator.java:164]: can you please remove the commented-out code.

**Review by amesbah — APPROVED** [review]
